/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { FundingNeed, ProductionRole, Project } from "./types";

export const PROJECTS_DATA: Project[] = [
  {
    id: "what-we-fed",
    title: "WHAT WE FED",
    tone: "Dark mythic creature RPG",
    description: "A Godot creature RPG roguelite about hunger, bonding, mutation pressure, music-driven escalation, tactical lane/sector combat, and becoming the thing other creatures fear.",
    tags: ["Creature RPG", "Godot", "Mutation", "Bond vs Eat", "Combat Audio", "Dark Fantasy"],
    status: "Active Systems Pass",
    accentColor: "neon-green",
    publicVisual: {
      style: "wild-fable",
      mediaState: "RUNTIME_ASSET",
      mediaLabel: "assets/ui/shell/title_sigil.png",
      heading: "WHAT WE FED title sigil",
      note: "First-party runtime asset from the current WHAT WE FED repository, shown directly instead of a substitute dashboard illustration.",
      facets: ["320 × 320 PNG", "Runtime repository asset", "Source-linked"],
      asset: {
        src: "https://raw.githubusercontent.com/ultramonkey23/what-we-fed/master/assets/ui/shell/title_sigil.png",
        alt: "WHAT WE FED title sigil from the game's current public repository",
        width: 320,
        height: 320,
        sourceLabel: "title_sigil.png",
        sourceUrl: "https://github.com/ultramonkey23/what-we-fed/blob/master/assets/ui/shell/title_sigil.png",
      },
    },
    expandedDetails: "Current work focuses on combat readability, stable targeting, creature identity, progression pressure, and a stronger original audiovisual direction.",
    systemsUnderTheHood: [
      "Deterministic sector targeting resolves enemies by stable identity instead of brittle lane scans.",
      "Zone occupancy accounts for strikers and orbiters, reducing spawn and marker conflicts.",
      "Mutation and progression systems are being shaped around readable consequences rather than shallow labels.",
      "Original songs, combat backgrounds, impact VFX, sprites, UI panels, shell sigils, and shaders support the game's identity.",
    ],
  },
  {
    id: "bone-league",
    title: "Bone League: Black Bracket",
    tone: "Sports horror management sim",
    description: "A dark football roguelite management sim where doomed athletes are drafted into an 8-week Circle, matches resolve through layered simulation math, and every injury, upgrade, and roster decision can shape the season.",
    tags: ["Management Sim", "Roguelite", "Sports Horror", "Auto-Sim", "Strategy", "Procedural Seasons"],
    status: "Public Demo Live",
    accentColor: "electric-blue",
    publicVisual: {
      style: "necro-sport",
      mediaState: "PLAYABLE_DEMO",
      mediaLabel: "Playable browser build",
      heading: "Mythic Necro-Sport Anime",
      note: "Roster cards, bracket pressure, injury consequence, and named doomed athletes carry the current visual direction.",
      facets: ["Menus are the battlefield", "Dramatic roster identity", "Scoreboard clarity"],
    },
    demoUrl: "https://bone-league-black-bracket-604506170438.us-east1.run.app",
    demoLabel: "Play Bone League",
    expandedDetails: "Bone League demonstrates a direct browser-accessible game loop with draft pressure, roster management, strategic upgrades, persistent run state, procedural weeks, and readable simulation output.",
    systemsUnderTheHood: [
      "A single state store coordinates roster, run state, map nodes, meta progression, currency, histories, and routing.",
      "An eight-week procedural Circle structure creates branching pressure and championship endpoints.",
      "Layered simulation math resolves plays from athlete attributes and strategic context.",
      "Match reports translate simulation logs into readable sports-horror narrative.",
    ],
  },
  {
    id: "savage-crown",
    title: "Savage Crown",
    tone: "Mobile-native mutation roguelite",
    description: "A native Android action roguelite systems project where mutations, creatures, passives, projectiles, and stat growth fuse into a living Crownbeast identity.",
    tags: ["Android Native", "C++ Core", "Kotlin/JNI", "Mutation Draft", "Crownbeast", "Offline-First"],
    status: "Native Build / Visual Direction Active",
    accentColor: "crimson",
    publicVisual: {
      style: "crown-biology",
      mediaState: "NATIVE_BUILD",
      mediaLabel: "Native build proof",
      heading: "Crown Biology / Mathematical Mutation",
      note: "Generated anatomy, readable graft locations, and build-driven VisualStrain are implemented directions; final visual acceptance remains separate from build proof.",
      facets: ["Generated anatomy", "VisualStrain", "Body Before Power"],
    },
    expandedDetails: "Savage Crown is the studio's native technical track: deterministic C++ gameplay, Kotlin/JNI integration, offline-first runtime law, Android builds, and separately witnessed device validation.",
    systemsUnderTheHood: [
      "Biological UI wiring maps native simulation state into the Kotlin presentation layer.",
      "Dynamic resistance curves support long-form leveling without shallow linear hardcaps.",
      "JNI hot paths reduce overhead across the native/mobile bridge.",
      "Gameplay remains independent from network services, API keys, quotas, or cloud calls.",
    ],
  },
  {
    id: "saga-anxious-fluff",
    title: "Saga of an Anxious Fluff",
    tone: "Colorful sensory-aware RPG",
    description: "A family-facing creature-growth RPG dedicated to Cody's son, proving accessible and sensory-aware games can still carry deep progression and satisfying system math.",
    tags: ["All-Ages RPG", "Creature Growth", "Family-Friendly", "Progression", "Sensory-Aware"],
    status: "Design / Early Build",
    accentColor: "warm-amber",
    publicVisual: {
      style: "all-ages-mythic",
      mediaState: "EARLY_BUILD",
      mediaLabel: "Early build",
      heading: "All-Ages Mythic Color",
      note: "Bright disciplined color, iconic silhouettes, emotional clarity, and transformation energy without flattening the project into preschool design.",
      facets: ["Sensory-aware", "Iconic transformation", "Warm adventure"],
    },
    expandedDetails: "This branch concentrates the studio's accessibility work: predictable loops, gentle audio control, readable emotion, steady visuals, and mechanical depth without harsh sensory pressure.",
  },
  {
    id: "feral-formation",
    title: "Feral Formation",
    tone: "Tactical creature-party roguelite",
    description: "A tactical creature-party roguelite where squad management, tempo control, clash windows, adaptive rewards, and formation strategy decide the run.",
    tags: ["Tactical RPG", "Creature Party", "Roguelite", "Formation Systems", "Deterministic Combat"],
    status: "Public Demo Live",
    accentColor: "violet",
    publicVisual: {
      style: "cosmic-slate",
      mediaState: "PLAYABLE_DEMO",
      mediaLabel: "Playable browser build",
      heading: "Cosmic Slate / Dark Field Archive",
      note: "Warband presence, ritual recruitment, clear action hierarchy, and restrained cosmic texture define the preserved visual direction.",
      facets: ["Warband Presence Strip", "Instinct decisions", "Mobile hierarchy"],
    },
    demoUrl: "https://feral-formation-604506170438.us-east1.run.app",
    demoLabel: "Play Feral Formation",
    expandedDetails: "Feral Formation is a mobile-first creature-party roguelite with deterministic combat, clash windows, adaptive rewards, persistent creature mastery, matchup forecasting, and formation-driven strategy.",
  },
  {
    id: "box-o-battles",
    title: "Box o' Battles",
    tone: "Evidence-aware matchup analysis",
    description: "A standalone Arbiter project that locks versions and scenarios, builds evidence-backed permanent-defeat routes, and produces structured matchup verdict packets.",
    tags: ["Arbiter", "Evidence-Aware", "Permanent-Defeat Routes", "Matchup Analysis", "Read-Only Consumer"],
    status: "BOB #003 Public Card Packet",
    accentColor: "warm-amber",
    publicVisual: {
      style: "arbiter-card",
      mediaState: "READ_ONLY_PACKET",
      mediaLabel: "BOB #003",
      heading: "Arbiter Card / Comic HUD v0.3",
      note: "The Box o' Battles repository owns the immutable card packet. Studios renders its Card Front, Card Back, Comic Panel Flow, Issue Variants, and Replay Seal read-only.",
      facets: ["Balance Blade", "Victory Depth", "Hinge Gate"],
    },
    expandedDetails: "The Box o' Battles repository owns evidence ingestion, evaluation, schema validation, and packet generation. The Studios website presents the owner-held BOB #003 packet without implementing a competing evaluator.",
    systemsUnderTheHood: [
      "Identity Bar locks versions, scenario, calibration, Math Spine version, and workflow version.",
      "Conversion Spines preserve Access, Interaction, Effect, Permanence, Repeatability, and Behavior in order.",
      "Victory Depth keeps field victory, anchor state, and essence finality separate.",
      "Issue Variants are stored branches with distinct outputs; Studios does not recompute them.",
    ],
  },
];

export const PRODUCTION_ROLES: ProductionRole[] = [
  { title: "Systems Design", roleDescription: "Architecting game economies, creature mutation trees, stat scaling structures, and roguelite progression loops.", iconName: "Palette", howAiHelps: "Models curves, flags balance outliers, and turns rough systems intent into testable structures." },
  { title: "Code & Debugging", roleDescription: "Building gameplay logic, rendering blocks, input listeners, state modules, and platform-specific bridges.", iconName: "Terminal", howAiHelps: "Accelerates implementation and audits while Cody keeps architecture and final behavior under human control." },
  { title: "Art Direction", roleDescription: "Drafting mood targets, creature silhouettes, color systems, interface texture, and visual identity references.", iconName: "Layers", howAiHelps: "Generates candidate visual directions that are filtered through the studio's specific horror and underground taste." },
  { title: "Combat Logic", roleDescription: "Designing combat clocks, clash windows, targeting rules, deterministic action steps, and active creature moves.", iconName: "Cpu", howAiHelps: "Stress-tests edge cases and maps multi-agent flow so combat stays readable under pressure." },
  { title: "UI / UX Planning", roleDescription: "Creating touch maps, tactical dashboards, high-contrast menus, and responsive viewport structures.", iconName: "Eye", howAiHelps: "Runs layout stress checks and catches text, viewport, and state problems before they become public friction." },
  { title: "Documentation", roleDescription: "Turning design notes, code decisions, and build proof into durable project memory.", iconName: "FileText", howAiHelps: "Collects scattered direction into readable specs, handoffs, and validation records." },
  { title: "Grant Materials", roleDescription: "Preparing public program pitches, support requests, budget reasoning, and compliance-friendly materials.", iconName: "Megaphone", howAiHelps: "Improves structure, vocabulary, clarity, and evidence trails for funders and incubators." },
  { title: "Playtest Analysis", roleDescription: "Parsing player logs, session reports, control friction, failure thresholds, and balance diagnostics.", iconName: "FlaskConical", howAiHelps: "Finds patterns in raw feedback and points iteration toward the highest-impact fixes." },
  { title: "Trailer / Marketing Prep", roleDescription: "Compiling hooks, teaser language, gameplay capture plans, transcripts, and sound timing notes.", iconName: "Megaphone", howAiHelps: "Drafts sharp public copy and campaign structures for high-identity indie communities." },
];

export const FUNDING_NEEDS: FundingNeed[] = [
  { title: "Dedicated Game-Development Workstation", description: "Hardware for local builds, engine work, asset prep, simulation testing, and faster iteration without phone-only bottlenecks.", urgency: "High Priority" },
  { title: "Drawing & Visual Production Tools", description: "Active display/tablet support and visual software for creature sheets, UI textures, pixel work, and original asset direction.", urgency: "High Priority" },
  { title: "Premium AI Production Tools", description: "Coding agents, analysis tools, regression helpers, image pipelines, and documentation systems for disciplined solo production.", urgency: "Strategic Pillar" },
  { title: "Original Asset Creation Support", description: "Custom sound effects, music support, creature art, animation help, voice/audio experiments, and tactile feedback polish.", urgency: "Strategic Pillar" },
  { title: "Playable Demo Development", description: "Polishing browser prototypes and native builds into clearer vertical slices for public testing, funders, and storefront preparation.", urgency: "High Priority" },
  { title: "Public-Facing Materials", description: "Pitch decks, manuals, short-form videos, technical summaries, screenshots, capture passes, and community-ready project pages.", urgency: "Mid Priority" },
];
