/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { FundingNeed, ProductionRole, Project } from "./types";

export const PROJECTS_DATA: Project[] = [
  {
    id: "what-we-fed",
    title: "WHAT WE FED",
    tone: "Dark mythic creature RPG",
    description: "A Godot creature RPG roguelite about hunger, bonding, mutation pressure, music-driven escalation, tactical lane/sector combat, and becoming the thing other creatures fear.",
    tags: ["Creature RPG", "Godot", "Mutation", "Bond vs Eat", "Combat Audio", "Dark Fantasy"],
    status: "Active Systems Pass / Showcase Capture Required",
    accentColor: "neon-green",
    publicVisual: {
      style: "what-we-fed",
      mediaState: "CAPTURE_REQUIRED",
      mediaLabel: "Showcase capture not promoted",
      heading: "LEGENDARY PIXEL FABLE INK",
      note: "The active visual direction is wondrous, mythic, strange, collectible, slightly eerie, and creature-first. Bone Ink belongs to corruption and escalation—not the default identity.",
      facets: ["Silhouette first", "Readable wonder", "Start weak, become feared"],
      evidence: [
        {
          id: "wwf-title-composition",
          title: "Current title composition",
          state: "CAPTURE_REQUIRED",
          note: "The live TitleScreen composes Ruins_world.png, a title rail, lair silhouette, particles, mist, and runtime typography. That composition—not one utility bitmap—is the public-facing subject.",
          limitation: "title_sigil.png is modulated to 34% as atmospheric support. It is intentionally withheld from the website because it is not representative standalone showcase art.",
          sourceLabel: "TitleScreen.gd",
          sourceUrl: "https://github.com/ultramonkey23/what-we-fed/blob/master/scenes/ui/TitleScreen.gd",
        },
      ],
    },
    expandedDetails: "The repository already contains runtime backgrounds, creature sprites, combat panels, impact art, capture tooling, and visual-audit receipts. A current approved scene capture should be selected from that full composition rather than promoting a small support asset by filename.",
    systemsUnderTheHood: [
      "Deterministic sector targeting resolves enemies by stable identity instead of brittle lane scans.",
      "Zone occupancy accounts for strikers and orbiters, reducing spawn and marker conflicts.",
      "The Visual Truth Loop requires screenshots, context metadata, readability notes, and before/after proof for visual promotion.",
      "The active style guide prioritizes creature silhouette, jewel-toned readability, evolution continuity, and corruption as a bounded escalation layer.",
    ],
  },
  {
    id: "bone-league",
    title: "Bone League: Black Bracket",
    tone: "Sports horror management sim",
    description: "A dark football roguelite management sim where doomed athletes are drafted into an 8-week Circle, matches resolve through layered simulation math, and every injury, upgrade, and roster decision can shape the season.",
    tags: ["Management Sim", "Roguelite", "Sports Horror", "Auto-Sim", "Strategy", "Procedural Seasons"],
    status: "Public Demo Live",
    accentColor: "electric-blue",
    publicVisual: {
      style: "bone-league",
      mediaState: "PLAYABLE_DEMO",
      mediaLabel: "Playable browser build",
      heading: "Bone League: Black Bracket",
      note: "The playable build—not an invented style nickname—is the current public visual authority. A dedicated screenshot pass remains the next media upgrade.",
      facets: ["Draft pressure", "Roster management", "Match reports"],
    },
    demoUrl: "https://bone-league-black-bracket-604506170438.us-east1.run.app",
    demoLabel: "Play Bone League",
    expandedDetails: "Bone League demonstrates a direct browser-accessible game loop with draft pressure, roster management, strategic upgrades, persistent run state, procedural weeks, and readable simulation output.",
    systemsUnderTheHood: [
      "A single state store coordinates roster, run state, map nodes, meta progression, currency, histories, and routing.",
      "An eight-week procedural Circle structure creates branching pressure and championship endpoints.",
      "Layered simulation math resolves plays from athlete attributes and strategic context.",
      "Match reports translate simulation logs into readable sports-horror narrative.",
    ],
  },
  {
    id: "savage-crown",
    title: "Savage Crown",
    tone: "Mobile-native mutation roguelite",
    description: "A native Android action roguelite where mutations, creatures, passives, projectiles, and stat growth fuse into persistent generated-life identity.",
    tags: ["Android Native", "C++ Core", "Kotlin/JNI", "Mutation Draft", "Crownbeast", "Offline-First"],
    status: "Installed Baseline / Newer Device Proof Pending",
    accentColor: "crimson",
    publicVisual: {
      style: "savage-crown",
      mediaState: "NATIVE_BUILD",
      mediaLabel: "Evidence-ranked visual library",
      heading: "Body-First Visual Engine",
      note: "CHARACTER BEFORE EFFECT: morphable authored life and procedural energy. Build proof, runtime promotion, device-partial candidates, references, and final visual acceptance remain separate states.",
      facets: ["Character before effect", "Morphable authored life", "Procedural energy"],
      evidence: [
        {
          id: "sc-world-plane",
          title: "GL-WORLD-RUINED-DIVINE-MACHINE-001",
          state: "PROMOTED_RUNTIME_ENVIRONMENT",
          note: "Authored ruined-divine-machine combat plane with an off-center broken crown engine, five altar teeth, an incomplete trial ring, outer cyan rails, and a quiet central combat basin.",
          limitation: "The plane is deliberately subdued and supplies no telegraphs, ownership colors, damage, or status truth.",
          sourceLabel: "Savage Crown repository (private owner)",
        },
        {
          id: "sc-anatomy-atlas",
          title: "GL-BODY-PLANS-001 + GL-ANATOMY-001",
          state: "WIRED_RUNTIME_CANDIDATE_DEVICE_PARTIAL",
          note: "Six matched early/evolved body plans plus paired skull and support masks are wired through stable-ID selection, compatibility tags, renderer payloads, and fallback behavior.",
          limitation: "Contract and device execution pass, but same-ID evolution and dense-scene readability remain partial; the visual examiner score is 8/24.",
          sourceLabel: "Savage Crown repository (private owner)",
        },
        {
          id: "sc-gl-001-reference",
          title: "GL-001 Generated-Life Reference",
          state: "ACCEPTED_REFERENCE",
          note: "Accepted for material toughness, palette, armor vocabulary, evolution staging, and ruined-machine motifs.",
          limitation: "Reference only: dragon-body convergence, side-heavy views, runtime-detail collapse, and an overly conventional humanoid player prevent direct promotion.",
          sourceLabel: "Savage Crown repository (private owner)",
        },
      ],
    },
    expandedDetails: "Hybrid Visual Overhaul v0.1.53 is installed on the Pixel baseline. The newer Den witnessed-birth slice is locally validated and APK-assembled but still lacks commit-identical install, screenshots, bounded logcat, accessibility interaction proof, and human visual acceptance.",
    systemsUnderTheHood: [
      "Stable ID, continuous genome/stat pressure, evolution testimony, and live state own generated-life identity.",
      "Dimensional Carry supplies the base-3 ascension wall and shared anatomy/shard rank without the deleted dynamic-resistance path.",
      "VisualStrain reads live elasticity, entropy, and discordance rather than categorical DNA labels.",
      "Authored environment, body grammar, and procedural effects stay in separate semantic lanes under a bounded draw-pass budget.",
    ],
  },
  {
    id: "saga-anxious-fluff",
    title: "Saga of an Anxious Fluff",
    tone: "Colorful sensory-aware RPG",
    description: "A family-facing creature-growth RPG dedicated to Cody's son, exploring how sensory-aware design could support deep progression and satisfying system math. Accessibility outcomes remain untested.",
    tags: ["All-Ages RPG", "Creature Growth", "Family-Friendly", "Progression", "Sensory-Aware"],
    status: "Design / Early Build",
    accentColor: "warm-amber",
    publicVisual: {
      style: "saga-anxious-fluff",
      mediaState: "EARLY_BUILD",
      mediaLabel: "Early build",
      heading: "Saga of an Anxious Fluff",
      note: "The current public claim is an early sensory-aware creature-growth direction. Approved project artwork or a current build capture has not yet been attached to this card.",
      facets: ["Sensory-aware", "Creature growth", "Family-facing"],
    },
    expandedDetails: "This branch concentrates the studio's accessibility work: predictable loops, gentle audio control, readable emotion, steady visuals, and mechanical depth without harsh sensory pressure.",
  },
  {
    id: "feral-formation",
    title: "Feral Formation",
    tone: "Tactical creature-party roguelite",
    description: "A tactical creature-party roguelite where squad management, tempo control, clash windows, adaptive rewards, and formation strategy decide the run.",
    tags: ["Tactical RPG", "Creature Party", "Roguelite", "Formation Systems", "Deterministic Combat"],
    status: "Public Demo Live",
    accentColor: "violet",
    publicVisual: {
      style: "feral-formation",
      mediaState: "PLAYABLE_DEMO",
      mediaLabel: "Playable browser build",
      heading: "Feral Formation",
      note: "The current playable browser build is the public authority. A direct current screenshot should replace the no-media state after capture and review.",
      facets: ["Creature party", "Formation strategy", "Deterministic combat"],
    },
    demoUrl: "https://feral-formation-604506170438.us-east1.run.app",
    demoLabel: "Play Feral Formation",
    expandedDetails: "Feral Formation is a mobile-first creature-party roguelite with deterministic combat, clash windows, adaptive rewards, persistent creature mastery, matchup forecasting, and formation-driven strategy.",
  },
  {
    id: "box-o-battles",
    title: "Box o' Battles",
    tone: "Evidence-aware matchup analysis",
    description: "Choose version-locked fighters and an arena to inspect matchup candidates from the Box engine's pinned, precomputed matrix. Every result leads with the engine's win outlook — who wins and how likely, a model estimate labeled NOT CANON. Reviewed verdicts are shown separately when available.",
    tags: ["Arbiter", "Evidence-Aware", "Permanent-Defeat Routes", "Matchup Matrix", "Win Outlook", "Reviewed Verdicts"],
    status: "Interactive Precomputed Matchup Matrix",
    accentColor: "warm-amber",
    publicVisual: {
      style: "box-o-battles",
      mediaState: "PRECOMPUTED_MATRIX",
      mediaLabel: "Choose a matchup",
      heading: "The Box Arena",
      note: "The owner engine exported every displayed result at a pinned commit and seed — including the win outlook, a model estimate labeled NOT CANON. Studios only looks up those results; its reviewed rulings appear alongside compiled candidates, including contradictions.",
      facets: ["Who wins, how likely", "Locked fighters", "Choose an arena", "Inspect the routes"],
    },
    expandedDetails: "The public arena reads an owner-exported matchup matrix. Its compiled candidates are not reviewed verdicts and never calibrated odds: each leads with the Math Spine's win outlook — who wins and how likely, a model estimate labeled NOT CANON, not canon truth. The four reviewed pairings in the matrix provide a limited comparison, not calibration for the full roster.",
    systemsUnderTheHood: [
      "The pinned matrix contains version-locked fighters, arena choices, route evidence, and seeded engine results.",
      "The browser selects a stored result; it does not run a second evaluator.",
      "Every result leads with the owner's win outlook — who wins and how likely — as a model estimate labeled NOT CANON.",
      "Reviewed verdicts are displayed separately so disagreement stays visible.",
      "Route share and evidence confidence are separate measurements and are not calibrated win probabilities.",
    ],
  },
  {
    id: "muttpit",
    title: "MUTTPIT",
    tone: "Async scrap-league auto-battler",
    description: "A browser auto-battler for mongrels with something to prove: thirty-six scarred, junk-armored dogs, each with a face and a grudge; kennels are exact builds, bouts are mailed in and resolved deterministically, and every outcome is a Verdict Packet anyone can re-derive. The Pit keeps the receipts.",
    tags: ["Auto-Battler", "Async PvP", "Play-By-Mail", "Deterministic", "Browser Game", "Pixel Comic"],
    status: "Public Build Live",
    accentColor: "warm-amber",
    publicVisual: {
      style: "muttpit",
      mediaState: "PLAYABLE_DEMO",
      mediaLabel: "Playable browser build",
      heading: "MUTTPIT",
      note: "The playable build is the visual authority. These are real runtime captures from the shipped build: the game was driven in an actual browser and screenshotted mid-run, not staged and not drawn.",
      facets: ["Mailed-in bouts", "Verdict Packets", "Bone Bracket"],
      evidence: [
        {
          id: "muttpit-kennel",
          title: "Kennel screen — runtime capture",
          state: "PROMOTED_RUNTIME_GAMEPLAY",
          note: "The kennel screen during a real browser run of the shipped build: each dog's look, temperament, strain, stats and editable bite order exactly as the player sees them.",
          src: "/assets/muttpit/kennel/capture.png",
          alt: "MUTTPIT kennel screen: four illustrated mongrels — a bucket-helmeted brute, a bat-eared grem, a chain-dragging cur and a patchwork mutt — with stats and bite orders",
          width: 1280,
          height: 757,
          sourceLabel: "Shipped MUTTPIT browser build",
          sourceUrl: "/play/muttpit/",
        },
        {
          id: "muttpit-bout",
          title: "League bout — runtime capture",
          state: "PROMOTED_RUNTIME_GAMEPLAY",
          note: "A Bone Bracket week bout in the real browser build, captured on an actual impact frame: dogs face off in the Pit, statuses and targets show on the fighters, and the full deterministic log stays open underneath.",
          src: "/assets/muttpit/bout/capture.png",
          alt: "MUTTPIT bout mid-impact: two teams of illustrated junkyard dogs facing off in a fenced dirt pit, a damage burst on the front dog, nameplates with grit bars, and the bout log below",
          width: 1280,
          height: 757,
          sourceLabel: "Shipped MUTTPIT browser build",
          sourceUrl: "/play/muttpit/",
        },
        {
          id: "muttpit-mailbox",
          title: "Mailbox challenge — runtime capture",
          state: "PROMOTED_RUNTIME_GAMEPLAY",
          note: "The play-by-mail mailbox: import an opponent's kennel code, resolve the bout, and mail the Verdict Packet back for audit.",
          src: "/assets/muttpit/mailbox/capture.png",
          alt: "MUTTPIT mailbox screen with opponent code input and verdict packet audit",
          width: 1280,
          height: 757,
          sourceLabel: "Shipped MUTTPIT browser build",
          sourceUrl: "/play/muttpit/",
        },
        {
          id: "muttpit-title",
          title: "Title screen — runtime capture",
          state: "PROMOTED_RUNTIME_GAMEPLAY",
          note: "The title screen of the shipped build: key art of the six strains squaring off in the Pit, over the bone, rust and gold comic interface.",
          limitation: "Dog and key art are AI-assisted illustrations (local FLUX.2 Klein), art-directed, curated, retouched and size-optimized by the studio; interface, typography and all game text are authored in code.",
          src: "/assets/muttpit/title/capture.png",
          alt: "MUTTPIT title screen: a hulking hubcap-armored bulldog flanked by a skeletal hound, a hairless gremlin dog, a bloody-grinned cur and a goggled puppy, under the MUTTPIT logo",
          width: 1280,
          height: 757,
          sourceLabel: "Shipped MUTTPIT browser build",
          sourceUrl: "/play/muttpit/",
        },
      ],
    },
    demoUrl: "/play/muttpit/",
    demoLabel: "Play MUTTPIT",
    expandedDetails: "MUTTPIT ships as a static browser build that stands on its own: deterministic seeded battles that replay identically anywhere, Kennel Codes you can mail to a friend, Verdict Packets that fail audit the moment anyone tampers with them, and an 8-week Bone Bracket season against ghost kennels with their own personalities and schedules.",
    systemsUnderTheHood: [
      "Battle resolution is pure deterministic simulation: same kennels, same seed, same event log, same replay hash on any machine.",
      "Async PvP is real play-by-mail: export a Kennel Code, import the opponent's, resolve locally, and exchange an auditable Verdict Packet.",
      "A dog is a version-locked build — strain, stats, scars, and bite order change what it is; its authored look is who it is, and never changes a verdict.",
      "The Bone Bracket season runs against procedurally drafted ghost kennels with standings, scars between weeks, and promotion pressure.",
    ],
  },
];

export const PRODUCTION_ROLES: ProductionRole[] = [
  { title: "Systems Design", roleDescription: "Architecting game economies, creature mutation trees, stat scaling structures, and roguelite progression loops.", iconName: "Palette", howAiHelps: "Models curves, flags balance outliers, and turns rough systems intent into testable structures." },
  { title: "Code & Debugging", roleDescription: "Building gameplay logic, rendering blocks, input listeners, state modules, and platform-specific bridges.", iconName: "Terminal", howAiHelps: "Accelerates implementation and audits while Cody keeps architecture and final behavior under human control." },
  { title: "Art Direction", roleDescription: "Drafting mood targets, creature silhouettes, color systems, interface texture, and visual identity references.", iconName: "Layers", howAiHelps: "Generates candidate directions that remain candidates until repository ownership, visual proof, and Cody's acceptance promote them." },
  { title: "Combat Logic", roleDescription: "Designing combat clocks, clash windows, targeting rules, deterministic action steps, and active creature moves.", iconName: "Cpu", howAiHelps: "Stress-tests edge cases and maps multi-agent flow so combat stays readable under pressure." },
  { title: "UI / UX Planning", roleDescription: "Creating touch maps, tactical dashboards, high-contrast menus, and responsive viewport structures.", iconName: "Eye", howAiHelps: "Runs layout stress checks and catches text, viewport, and state problems before they become public friction." },
  { title: "Documentation", roleDescription: "Turning design notes, code decisions, and build proof into durable project memory.", iconName: "FileText", howAiHelps: "Collects scattered direction into readable specs, handoffs, and validation records." },
  { title: "Grant Materials", roleDescription: "Preparing public program pitches, support requests, budget reasoning, and compliance-friendly materials.", iconName: "Megaphone", howAiHelps: "Improves structure, vocabulary, clarity, and evidence trails for funders and incubators." },
  { title: "Playtest Analysis", roleDescription: "Parsing player logs, session reports, control friction, failure thresholds, and balance diagnostics.", iconName: "FlaskConical", howAiHelps: "Finds patterns in raw feedback and points iteration toward the highest-impact fixes." },
  { title: "Trailer / Marketing Prep", roleDescription: "Compiling hooks, teaser language, gameplay capture plans, transcripts, and sound timing notes.", iconName: "Megaphone", howAiHelps: "Drafts public copy and capture structures after the underlying proof state is known." },
];

export const FUNDING_NEEDS: FundingNeed[] = [
  { title: "Dedicated Game-Development Workstation", description: "Hardware for local builds, engine work, asset prep, simulation testing, and faster iteration without phone-only bottlenecks.", urgency: "High Priority" },
  { title: "Drawing & Visual Production Tools", description: "Active display/tablet support and visual software for creature sheets, UI textures, pixel work, and original asset direction.", urgency: "High Priority" },
  { title: "Premium AI Production Tools", description: "Coding agents, analysis tools, regression helpers, image pipelines, and documentation systems for disciplined solo production.", urgency: "Strategic Pillar" },
  { title: "Original Asset Creation Support", description: "Custom sound effects, music support, creature art, animation help, voice/audio experiments, and tactile feedback polish.", urgency: "Strategic Pillar" },
  { title: "Playable Demo Development", description: "Polishing browser prototypes and native builds into clearer vertical slices for public testing, funders, and storefront preparation.", urgency: "High Priority" },
  { title: "Public-Facing Materials", description: "Pitch decks, manuals, short-form videos, technical summaries, screenshots, capture passes, and community-ready project pages.", urgency: "Mid Priority" },
];
